controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

user_edit:
    path: '/user/edit/{id}'
    controller: App\Controller\UserprofileController::edit
    # methods: ['GET', 'POST']