controllers:
    resource: ../src/Controller/
    type: annotation
programme_details:
    path: /programme/{id}
    controller: App\Controller\ProgrammeController::show
programme_reservation:
    path: /reservation/{id}/{idd}/{idu}
    controller: App\Controller\ProgrammeController::reserv

kernel:
    resource: ../src/Kernel.php
    type: annotation

user_edit:
    path: '/user/edit/{id}'
    controller: App\Controller\UserprofileController::edit
    # methods: ['GET', 'POST']