controllers:
    resource: ../src/Controller/
    type: annotation
programme_details:
    path: /programme/{id}
    controller: App\Controller\ProgrammeController::show

kernel:
    resource: ../src/Kernel.php
    type: annotation

user_edit:
    path: '/user/edit/{id}'
    controller: App\Controller\UserprofileController::edit
    # methods: ['GET', 'POST']